config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.
  resources :categories
  root "homes#index"
  resources :films do
    resources :comments 
  end
  get "/rating/", to: "rating#index"
  resources :contacts
  resources :events
  resources :users
  get "/search/", to: "search#index"
  get "/auth/", to:"users#get_auth"
  post "/auth/", to:"users#set_auth"
  get "/code/", to:"users#check_code"
  get '/patients/:id', to: 'patients#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :films
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :film
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/film.rb
class Film < ApplicationRecord
    belongs_to :category
    has_many :comments
    has_one_attached :poster
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    before_create do
        (email == "main@mail.ru") ? self.admin = true : self.admin = false
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
    end

    def user_signed_in?
        current_user.present?
    end

    def user_admin?
        user_admin = false
        if current_user.present?
            user_admin = true if current_user.admin
        end
    end

    helper_method :current_user, :user_signed_in?
    helper_method :user_admin?, :user_admin?
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def show
        @films = Film.where(category_id: params[:id]).page params[:page]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        puts params
        @film = Film.find(params[:film_id])
        @comment = @film.comments.build(comment_params)
        if @comment.save 
            redirect_to film_path (@film)
        else
            render "films/show"
        end
    end
    
    private
    def comment_params
        params.require(:comment).permit(:user_name, :message)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    def create
        puts params
        @contact = Contact.new contact_params
        if @contact.save 
            redirect_to root_path
        else
            render :new
        end
    end

    private
    def contact_params
        params.require(:contact).permit(:name, :email, :comment)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def show
        @event = Event.find_by(id: params[:id])
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
    def show
        @film = Film.find(params[:id])
        @comment = @film.comments.build
        @comments = @film.comments.order(created_at: :desc)
    end

    def new 
        @film = Film.new
    end

    def create
        puts params
        @film = Film.new(film_params)
        if @film.save 
            redirect_to film_path @film
        else
            render :new
        end
    end

    private
    def film_params
        params.require(:film).permit(:name, :trailer_link, :rating, :year, :director, :description, :category_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index 
        @films = Category.find_by(name: "Фильмы").films.limit(4).order(created_at: :desc)
        @serial = Category.find_by(name: "Сериалы").films.limit(4).order(created_at: :desc)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    def show
        puts "*"*25
        puts params
        puts "*"*25
    end
end

app/controllers/rating_controller.rb
class RatingController < ApplicationController
    def index
        @films = Category.find_by(name: "Фильмы").films.limit(4).order(created_at: :desc)
        @serial = Category.find_by(name: "Сериалы").films.limit(4).order(created_at: :desc)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
        if params[:query].size > 0
            @films = Film.where("lower(name) like ?", "%#{params[:query].downcase}%")
        else
            @films = "слишком короткий поиск"
            # redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create # регистрация
        email = params['user']['email']
        @user = User.find_by(email: email) 
        if @user.present?
            flash[:danger] = "Такой пользователь уже существует!"
            render :new
        else
            @user = User.new(user_params) 
            if @user.save
                code = rand(100_000 .. 1_000_000).to_s
                @user.update!(code_active: code)
                UserMailer.with(email: @user.email, code: code).welcome_email.deliver_now
                flash[:notice] = "Поздравляю вы успешно зарегистрировались!"
                # session[:user_id] = @user.id
                redirect_to root_path
            end
        end
    end

    def index
        session.delete :user_id
        redirect_to root_path
    end

    def get_auth
        @user = User.new
    end

    def set_auth
        email = params['email']
        password = params['password']
        user = User.find_by(email: email)
        if user.nil?
            flash[:danger] = "Пользователь не найден!"
            redirect_to auth_path
        else
            if user.authenticate(password) && user.is_active
                flash[:notice] = "Поздравляю вы успешно авторизовались!"
                session[:user_id] = user.id
                redirect_to root_path
            elsif user.is_active == false
                flash[:danger] = "Для активации аккаунта проверьте почту!"
                redirect_to auth_path
            else
                flash[:danger] = "Пароль не верный!"
                redirect_to auth_path
            end
        end
    end

    # /code?email=123@mail.ru&code=123456
    def check_code
        email = params[:email]
        code = params[:code]
        user = User.find_by(email: email)
        if user.present?
            if user.is_active
                flash[:danger] = "Вы уже ранее активировали аккаунт!" 
            else
                if code == user.code_active
                    flash[:notice] = "Вы успешно активировали аккаунт!" 
                    user.update!(is_active: true)
                else
                    flash[:danger] = "Код не верный!"
                end
            end
        else
            flash[:danger] = "Данного пользователя не существует!"
        end
        redirect_to auth_path
    end


    private
    def user_params
        params.require(:user).permit(:email, :name, :password, :password_confirm)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def menu_helper
        categories = Category.all
        render partial: 'shared/menu', locals: { categories: categories }
    end

    def rating_helper
        films = Category.find_by(name: "Фильмы").films.limit(5).order(created_at: :desc)
        render partial: 'shared/rating', locals: { films: films }
    end

    def news_helper
        event = Event.last
        render partial: 'shared/news', locals: { event: event }
    end
end

app/views/admin/categories/_form.html.erb
<%= semantic_form_for [:admin, @category], builder: ActiveAdmin::FormBuilder do |f| %>
    <%= f.inputs do %>
        <%= f.input :name %>
    <% end %>
<% end %>

app/views/categories/show.html.erb
<%= paginate @films, window: 1 %>
<% @films.each do |film| %>
    <div class="info_film">
        <% if film.poster.attached? %>
            <%= image_tag film.poster %>
        <% else %>
        <% end %>
        <%= film.description.truncate(270) %>
        <div class="button"><%= link_to "Смотреть", film %></div>
    </div>
<% end %>
<%= paginate @films, window: 1 %>

app/views/comments/_comments.html.erb
<% if @comments.blank? %>
    Вы можете быть первым, кто оставит отзыв
<% else %>
    <% @comments.each do |comment| %>
        <div class="reviews">
            <div class="review_name">
                <%= comment.user_name %>
            </div>
            <div class="review_text">
                <%= comment.message %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/comments/_form.html.erb
<div class="send">
    <%= form_with model: [@film, @comment] do |f| %>
        <%= f.label "Имя пользователя" %>
        <%= f.text_field :user_name %>
        <%= f.label "Ваш отзыв" %>
        <%= f.text_area :message %>
        <%= f.submit "отправить" %>
    <% end %>
</div>

app/views/events/show.html.erb
<h2><a href="#"><%= @event.title %></a></h2>
<div class="posts_content">
    <p>
        <%= @event.body %>
    </p>

    <p>
        <%= @event.date_event %>
    </p>

</div>

app/views/films/_form.html.erb
<div class="creats_film">
    <%= form_with model: @film do |f| %>
        <%= f.text_field :name, placeholder: "Имя фильма" %>
        <%= f.text_field :trailer_link, placeholder: "Ссылка на трейлер" %>
        <%= f.number_field :rating, placeholder: "Рейтинг" %>
        <%= f.number_field :year, placeholder: "Год" %>
        <%= f.text_field :director, placeholder: "Имя директора" %>
        <%= f.text_field :description, placeholder: "Описание фильма" %>
        <%= f.number_field :category_id, placeholder: "Id фильма" %>
        <%= f.submit "Добавить фильм" %>
    <% end %>
</div>

app/views/films/new.html.erb
<h1>Новый фильм</h1>
<%= render 'form', film: @film %>

app/views/films/show.html.erb
<h1><%= @film.name %></h1>
<iframe width="560" height="315" src= <%= @film.trailer_link %> frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<div class="info_film_page">
    <span class="lable">Рейтинг: </span><span class="value"><%= @film.rating %></span>
    <span class="lable">Год: </span><span class="value"><%= @film.year %></span>
    <span class="lable">Режиссёр: </span><span class="value"><%= @film.director %></span>
</div>
<hr>
<h2>Описание фильма "<%= @film.name %>"</h2>
<div class="descriptions_film">
    <% if @film.poster.attached? %>
        <%= image_tag @film.poster %>
    <% end %>
    <%= @film.description %>
</div>
<hr>
<p>
<h2>Отзывы об фильме "<%= @film.name %>":</h2>
</p>

<%= render 'comments/comments' %>
<% if user_signed_in? %>
    <%= render 'comments/form' %>
<% else %>
    <hr>
    <p> 
    Отзыв может оставлять только зарегестрированный пользователь
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diplom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital@1&display=swap" rel="stylesheet">
    <meta name="viewport" content="width = divice-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main">
      <%= menu_helper %>
      <div class="site_content">
        <div class="sidebar_container">
          <%= render partial: 'shared/input' %>
          <%= render partial: 'shared/search'  %>
          <%= news_helper %>
          <%= rating_helper %>
        </div>
        <div class="content">

          <%= yield %>
          
        </div>
      </div>
      <%= render partial: 'shared/footer' %>
    </div>
  </body>
</html>

app/views/rating/index.html.erb
<table>
    <tr>
        <th></th>
        <th>Фильм</th>
        <th class="center">Год</th>
        <th class="center">Рейтинг</th>
    </tr>
    <% counter = 0 %>  
    <% @films.each do |film| %>
        <tr>
            <% if film.poster.attached? %>
            <td class="center"><%= image_tag film.poster %></td>
            <% end %>
            <% counter = counter + 1 %>
            <td><%= counter %>.&nbsp;<%= link_to film.name, film %></td>
            <td class="center"><%= film.year %></td>
            <td class="center rating"><%= film.rating %></td>
        </tr>
    <% end %>

</table>

app/views/search/index.html.erb
<% if @films == "слишком короткий поиск" %>
    <h3>слишком короткий поиск, воспользуйтесь формой поиска<h3>
<% elsif @films.size == 0 %>
    <h3>фильмы по-вашему запросу не найдены<h3>
<% else %>
    <% @films.each do |film| %>
        <div class="info_film">
            <% if film.poster.attached? %>
                <%= image_tag film.poster %>
            <% else %>
            <% end %>
            <%= film.description %>
            <div class="button"><%= link_to "Смотреть", film %></div>
        </div>
    <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <p>
        <a href="#">Главная</a>
        <a href="#">Фильмы</a>
        <a href="#">Сериалы</a>
        <a href="#">Рейтинг Фильмов</a>
        <a href="#">Контакты</a>
    </p>
    <p>
        <%= ENV['SHORT_HOST'] %> 2021-<%= Time.now.year %> 
    </p>
</div>

app/views/shared/_input.html.erb
<div class="sidebar">
    <% if user_signed_in? %>
        <h2>Здравствуйте</h2>
        <input type="text" placeholder="<%= current_user.name %>" readonly/>
        <input type="text" placeholder="<%= current_user.email %>" readonly/>
        <%= link_to "выйти", users_path %>
    <% else %>
        <h2>Вход</h2>
        <div class="lables_passreg_text">
            <span><%= link_to "авторизация", auth_path %></span>
        </div>
        <div class="lables_passreg_text">
            <span><%= link_to "регистрация", new_user_path %></span>
        </div>
    <% end %> 
</div>

app/views/shared/_menu.html.erb
<div class="header">
    <div class="logo">
    <div class="logo_text">
        <h1><a href="#">Онлайн Кино</a></h1> 
        <h2>Лучшие фильмы здесь</h2>
    </div>
    </div>
    <div class="menubar">
        <ul class="menu">
        <li><%= link_to "Главная", root_path %></li>
        <% categories.each do |category| %>
            <li><%= link_to category.name, category_path(category) %></li>
        <% end %>
        <li><%= link_to "Рейтинг", rating_path %></li>
        <li><%= link_to "Контакты", new_contact_path %></li>
        
        </ul>
    </div>
</div>

app/views/shared/_news.html.erb
<div class="sidebar">
    <h2>Новости</h2>
    <% if event.present? %>
        <span><%= event.date_event %></span>
        <p><%= link_to event.title, event %></p>
    <% else %>
        <p>Новостей нет, но скоро появятся</p>
    <% end %>
</div>

app/views/shared/_rating.html.erb
<div class="sidebar">
    <h2>Рейтинг фильмов</h2>
    <ul>
        <% if films.present? %>
            <% films.each do |film| %>
                <li><%= link_to film.name, film %> <span class="rating_sidebar"><%= film.rating %></span></li>
            <% end %>
        <% else %>
                фильмов пока нет
        <% end %>
    </ul>
</div>

app/views/shared/_search.html.erb
<div class="sidebar">
    <h2>Поиск</h2>

    <%= form_with url: "/search", method: :get do |form| %>
        <%= form.search_field :query, placeholder: "ваш запрос", minlength: "1" %>
        <%= form.submit "найти", class: "btn" %>
    <% end %>
</div>

app/views/users/get_auth.html.erb
<% if flash[:danger] %>
    <div class="danger"><%= flash[:danger] %></div>
<% end %>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="authount">    
    <%= form_with url: '/auth', method: :post do |f| %>
        <%= f.email_field :email, placeholder: "ваша почта", minlength: "6", :required => true %>
        <%= f.password_field :password, placeholder: "ваш пароль", minlength: "6", :required => true %>
        <%= f.submit "Авторизоваться" %>
    <% end %>
</div>

app/views/users/new.html.erb
<% if flash[:danger] %>
    <div class="danger"><%= flash[:danger] %></div>
<% end %>
<div class="register">
    <%= form_with model: @user do |f| %>
        <%= f.email_field :email, placeholder: "ваша почта", minlength: "6", :required => true %>
        <%= f.text_field :name, placeholder: "ваша имя", minlength: "4", :required => true %>
        <%= f.password_field :password, placeholder: "ваш пароль", minlength: "6", :required => true %>
        <%= f.submit "зарегестрироваться" %>
    <% end %>
</div>